# Generated by Django 4.1.3 on 2022-11-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_measurement_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
